import type { Listing, Order } from "./types";

export const LISTINGS: Listing[] = [
  {
    id: "1",
    title: "iPhone 15 Pro Max 256GB Natural Titanium",
    price: 520,
    condition: "Like New",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Minh Tuấn",
    sellerAvatar: "MT",
    sellerRating: 4.9,
    sellerSales: 38,
    location: "Quận 1, TP.HCM",
    likes: 47,
    isLiked: false,
    rating: 4.9,
    reviewCount: 38,
    category: "electronics",
    isFeatured: true,
    isHot: true,
    description: "Mua tháng 10/2024, dùng nhẹ văn phòng, không bao giờ rơi. 99% không trầy xước. Đầy đủ hộp phụ kiện Apple gốc. Bảo hành Apple Store còn 8 tháng. Kính dán ZAGG từ ngày mua.",
    postedAt: "2 giờ trước",
    colorAccent: "blue",
    views: 312,
  },
  {
    id: "2",
    title: "MacBook Air M2 8GB/512GB Midnight",
    price: 680,
    condition: "Like New",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Lan Anh",
    sellerAvatar: "LA",
    sellerRating: 5.0,
    sellerSales: 21,
    location: "Hoàn Kiếm, Hà Nội",
    likes: 83,
    isLiked: true,
    rating: 5.0,
    reviewCount: 21,
    category: "electronics",
    isFeatured: true,
    description: "Máy mua mới tháng 6/2024. Dùng văn phòng, không game. Pin còn 97%. Bao gồm sạc MagSafe 30W gốc và túi chống sốc.",
    postedAt: "5 giờ trước",
    colorAccent: "indigo",
    views: 198,
  },
  {
    id: "3",
    title: "Nike Air Jordan 1 Retro High OG Size 42",
    price: 95,
    condition: "Good",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Hoàng Nam",
    sellerAvatar: "HN",
    sellerRating: 4.7,
    sellerSales: 14,
    location: "Hải Châu, Đà Nẵng",
    likes: 29,
    isLiked: false,
    rating: 4.7,
    reviewCount: 14,
    category: "fashion",
    description: "Giày chính hãng mua tại SNKRS app. Dùng 3 tháng, còn đẹp 90%. Kèm hộp gốc và đế phụ.",
    postedAt: "Hôm qua",
    colorAccent: "red",
    views: 87,
  },
  {
    id: "4",
    title: "Sony A7 III + Lens 28-70mm Kit",
    price: 890,
    condition: "Good",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Thu Hà",
    sellerAvatar: "TH",
    sellerRating: 4.8,
    sellerSales: 9,
    location: "Ninh Kiều, Cần Thơ",
    likes: 56,
    isLiked: false,
    rating: 4.8,
    reviewCount: 9,
    category: "electronics",
    isFeatured: true,
    isHot: true,
    description: "Body Sony A7 III chụp khoảng 25k shot. Lens nguyên zin chưa sửa. Full hộp, sạc, túi. Kèm thêm 2 pin Sony gốc và túi đựng máy.",
    postedAt: "3 giờ trước",
    colorAccent: "zinc",
    views: 145,
  },
  {
    id: "5",
    title: "Sofa da thật 3 chỗ nhập Malaysia",
    price: 185,
    condition: "Good",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Đức Mạnh",
    sellerAvatar: "DM",
    sellerRating: 4.4,
    sellerSales: 6,
    location: "Bình Thạnh, TP.HCM",
    likes: 18,
    isLiked: false,
    rating: 4.4,
    reviewCount: 6,
    category: "home",
    description: "Sofa da thật nhập khẩu Malaysia. Dùng 2 năm, da không bong tróc, đệm vẫn đàn hồi tốt. Màu nâu caramel sang trọng.",
    postedAt: "2 ngày trước",
    colorAccent: "amber",
    views: 64,
  },
  {
    id: "6",
    title: 'Samsung QLED 55" 4K Smart TV 2023',
    price: 420,
    condition: "Like New",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Phương Linh",
    sellerAvatar: "PL",
    sellerRating: 4.6,
    sellerSales: 11,
    location: "Đống Đa, Hà Nội",
    likes: 34,
    isLiked: true,
    rating: 4.6,
    reviewCount: 11,
    category: "electronics",
    description: "TV còn bảo hành hãng 18 tháng. Dùng ít, hình ảnh sắc nét. Kèm remote và chân đế gốc.",
    postedAt: "Hôm qua",
    colorAccent: "sky",
    views: 110,
  },
  {
    id: "7",
    title: "Honda Wave Alpha 2022 Đỏ Đen",
    price: 920,
    condition: "Good",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Thanh Long",
    sellerAvatar: "TL",
    sellerRating: 4.8,
    sellerSales: 17,
    location: "Thủ Đức, TP.HCM",
    likes: 72,
    isLiked: false,
    rating: 4.8,
    reviewCount: 17,
    category: "vehicles",
    isFeatured: true,
    description: "Xe đi khoảng 18.000 km. Máy êm, không hao dầu. Giấy tờ xe đầy đủ, sang tên ngay. Xe không tai nạn ngập nước.",
    postedAt: "4 giờ trước",
    colorAccent: "red",
    views: 223,
  },
  {
    id: "8",
    title: "iPad Air 5 Wi-Fi 64GB + Apple Pencil 2",
    price: 380,
    condition: "Like New",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Bích Trâm",
    sellerAvatar: "BT",
    sellerRating: 4.9,
    sellerSales: 23,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    likes: 41,
    isLiked: false,
    rating: 4.9,
    reviewCount: 23,
    category: "electronics",
    description: "iPad mua tháng 1/2025. Dùng học online. Pin còn 98%. Kèm Apple Pencil 2 và bao da Smart Folio.",
    postedAt: "6 giờ trước",
    colorAccent: "indigo",
    views: 167,
  },
  {
    id: "9",
    title: "Bộ bàn ăn gỗ sồi 6 ghế Bắc Âu",
    price: 240,
    condition: "Good",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Ngọc Hà",
    sellerAvatar: "NH",
    sellerRating: 4.5,
    sellerSales: 4,
    location: "Long Biên, Hà Nội",
    likes: 22,
    isLiked: false,
    rating: 4.5,
    reviewCount: 4,
    category: "home",
    description: "Bàn ăn gỗ sồi nguyên khối, thiết kế Scandinavian. Vài vết xước nhỏ ở mép bàn. Có thể tháo rời vận chuyển.",
    postedAt: "3 ngày trước",
    colorAccent: "amber",
    views: 51,
  },
  {
    id: "10",
    title: "Áo khoác The North Face Nuptse 700 Size L",
    price: 130,
    condition: "Like New",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Việt Anh",
    sellerAvatar: "VA",
    sellerRating: 4.8,
    sellerSales: 8,
    location: "Cầu Giấy, Hà Nội",
    likes: 35,
    isLiked: false,
    rating: 4.8,
    reviewCount: 8,
    category: "fashion",
    description: "Áo hàng chính hãng mua tại Mỹ. Mặc 2 mùa đông, giặt khô sạch sẽ, phồng như mới. Size L phù hợp 60-75kg.",
    postedAt: "1 ngày trước",
    colorAccent: "zinc",
    views: 94,
  },
  {
    id: "11",
    title: "Bộ loa Sonos Era 300 Trắng",
    price: 310,
    condition: "Like New",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Quang Huy",
    sellerAvatar: "QH",
    sellerRating: 4.7,
    sellerSales: 5,
    location: "Tân Bình, TP.HCM",
    likes: 28,
    isLiked: false,
    rating: 4.7,
    reviewCount: 5,
    category: "electronics",
    description: "Loa Sonos Era 300 stereo âm thanh vòm Dolby Atmos. Mua tháng 3/2025. Dùng phòng khách, không có xước.",
    postedAt: "8 giờ trước",
    colorAccent: "sky",
    views: 78,
  },
  {
    id: "12",
    title: "Xe đạp Giant ATX 830 Size M",
    price: 145,
    condition: "Good",
    image: "/placeholder.svg?height=400&width=400",
    seller: "Hải Long",
    sellerAvatar: "HL",
    sellerRating: 4.3,
    sellerSales: 3,
    location: "Liên Chiểu, Đà Nẵng",
    likes: 19,
    isLiked: false,
    rating: 4.3,
    reviewCount: 3,
    category: "sports",
    description: "Xe đạp địa hình Giant 27.5 inch. Đi khoảng 200km, bảo dưỡng đều đặn. Chưa bao giờ ngã. Lốp xe còn mới.",
    postedAt: "5 ngày trước",
    colorAccent: "green",
    views: 42,
  },
];

export const ORDERS: Order[] = [
  {
    id: "o1",
    title: "iPhone 15 Pro Max 256GB",
    price: 520,
    image: "/placeholder.svg?height=100&width=100",
    counterparty: "Minh Tuấn",
    counterpartyAvatar: "MT",
    status: "shipping",
    date: "14/03/2026",
    type: "buying",
    category: "electronics",
  },
  {
    id: "o2",
    title: "Sofa da thật 3 chỗ Malaysia",
    price: 185,
    image: "/placeholder.svg?height=100&width=100",
    counterparty: "Đức Mạnh",
    counterpartyAvatar: "DM",
    status: "pending",
    date: "13/03/2026",
    type: "buying",
    category: "home",
  },
  {
    id: "o3",
    title: "Nike Air Jordan 1 Retro High",
    price: 95,
    image: "/placeholder.svg?height=100&width=100",
    counterparty: "Bách Nguyễn",
    counterpartyAvatar: "BN",
    status: "completed",
    date: "10/03/2026",
    type: "selling",
    category: "fashion",
  },
  {
    id: "o4",
    title: "Sony WH-1000XM5 Headphones",
    price: 110,
    image: "/placeholder.svg?height=100&width=100",
    counterparty: "Khánh Ly",
    counterpartyAvatar: "KL",
    status: "cancelled",
    date: "08/03/2026",
    type: "selling",
    category: "electronics",
  },
  {
    id: "o5",
    title: "MacBook Air M1 2020 Space Grey",
    price: 490,
    image: "/placeholder.svg?height=100&width=100",
    counterparty: "Bảo Trần",
    counterpartyAvatar: "BT",
    status: "completed",
    date: "05/03/2026",
    type: "buying",
    category: "electronics",
  },
  {
    id: "o6",
    title: "Áo khoác North Face Nuptse",
    price: 130,
    image: "/placeholder.svg?height=100&width=100",
    counterparty: "Minh Đức",
    counterpartyAvatar: "MD",
    status: "confirmed",
    date: "15/03/2026",
    type: "buying",
    category: "fashion",
  },
  {
    id: "o7",
    title: "iPad Air 5 Wi-Fi 64GB",
    price: 380,
    image: "/placeholder.svg?height=100&width=100",
    counterparty: "Thu Trang",
    counterpartyAvatar: "TT",
    status: "confirmed",
    date: "12/03/2026",
    type: "selling",
    category: "electronics",
  },
];

export const CATEGORIES = [
  { id: "all",         label: "Tất cả",     emoji: "🛍️" },
  { id: "electronics", label: "Điện tử",    emoji: "📱" },
  { id: "fashion",     label: "Thời trang", emoji: "👟" },
  { id: "home",        label: "Nội thất",   emoji: "🛋️" },
  { id: "vehicles",    label: "Xe cộ",      emoji: "🏍️" },
  { id: "books",       label: "Sách",       emoji: "📚" },
  { id: "sports",      label: "Thể thao",   emoji: "⚽" },
];

export const CARD_COLOR: Record<string, { imageBg: string }> = {
  blue:   { imageBg: "bg-blue-50"   },
  indigo: { imageBg: "bg-indigo-50" },
  red:    { imageBg: "bg-red-50"    },
  zinc:   { imageBg: "bg-zinc-100"  },
  amber:  { imageBg: "bg-amber-50"  },
  sky:    { imageBg: "bg-sky-50"    },
  green:  { imageBg: "bg-green-50"  },
  violet: { imageBg: "bg-violet-50" },
};

export const CONDITION_CFG: Record<string, { label: string; cls: string }> = {
  New:        { label: "Mới",       cls: "bg-success-soft text-success" },
  "Like New": { label: "Như mới",   cls: "bg-brand-soft text-primary"  },
  Good:       { label: "Tốt",       cls: "bg-pi-gold-soft text-pi-gold" },
  Fair:       { label: "Trung bình",cls: "bg-muted text-muted-foreground" },
};
